accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.create, name="create"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:pk>/profile/", views.profile, name="profile"),
    path("profile/update/", views.profile_update, name="profile_update"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("store/", views.store, name="store"),
    path("<int:store_pk>/", views.store_detail, name="store_detail"),
    path("<int:store_pk>/delete", views.store_delete, name="store_delete"),
    path("<int:store_pk>/update", views.store_update, name="store_update"),
    path("<int:store_pk>/review_create/", views.review_create, name="review_create"),
    path(
        "<int:store_pk>/<int:review_pk>/review_detail/",
        views.review_detail,
        name="review_detail",
    ),
    path(
        "<int:store_pk>/<int:review_pk>/review_delete/",
        views.review_delete,
        name="review_delete",
    ),
    path(
        "<int:store_pk>/<int:review_pk>/review_detail/review_update/",
        views.review_update,
        name="review_update",
    ),
    path("search/", views.search, name="search"),
    path(
        "<int:store_pk>/<int:review_pk>/review_detail/comment/",
        views.comment_create,
        name="comment_create",
    ),
    path(
        "<int:store_pk>/<int:review_pk>/review_detail/comment/<int:comment_pk>/comment_delete",
        views.comment_delete,
        name="comment_delete",
    ),
    path("local_list/", views.local_list, name="local_list"),
    path("local_list/local_detail_gn", views.local_detail_gn, name="local_detail_gn"),
    path("local_list/local_detail_sc", views.local_detail_sc, name="local_detail_sc"),
    path("local_list/local_detail_ys", views.local_detail_ys, name="local_detail_ys"),
    path("local_list/local_detail_sd", views.local_detail_sd, name="local_detail_sd"),
    path("local_list/local_detail_no", views.local_detail_no, name="local_detail_no"),
    path("local_list/local_detail_dj", views.local_detail_dj, name="local_detail_dj"),
    path("local_list/local_detail_sp", views.local_detail_sp, name="local_detail_sp"),
    path("local_list/local_detail_jn", views.local_detail_jn, name="local_detail_jn"),
    path("price_list/", views.price_list, name="price_list"),
    path(
        "price_list/price_detail_1man",
        views.price_detail_1man,
        name="price_detail_1man",
    ),
    path(
        "price_list/price_detail_2man",
        views.price_detail_2man,
        name="price_detail_2man",
    ),
    path(
        "price_list/price_detail_3man",
        views.price_detail_3man,
        name="price_detail_3man",
    ),
    path(
        "price_list/price_detail_4man",
        views.price_detail_4man,
        name="price_detail_4man",
    ),
    path(
        "price_list/price_detail_4manup",
        views.price_detail_4manup,
        name="price_detail_4manup",
    ),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.conf import settings


class User(AbstractUser):
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )


class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(
        default="noimg.jpg",
        blank=True,
        processors=[Thumbnail(300, 300)],
        format="JPEG",
        options={"quality": 50},
    )

reviews/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings


# Create your models here.
class Store(models.Model):
    store_name = models.CharField(max_length=80)
    address = models.CharField(max_length=160)
    phone_num = models.CharField(max_length=80)
    menu = models.CharField(max_length=80)
    price = models.CharField(max_length=80, null=True, blank=True)
    parking = models.CharField(max_length=80, null=True, blank=True)
    week_time = models.CharField(max_length=80, null=True, blank=True)
    weekend = models.CharField(max_length=80, null=True, blank=True)
    last_order = models.CharField(max_length=80, null=True, blank=True)
    website = models.CharField(max_length=80, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(
        default="nostoreimg.jpg",
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 90},
    )
    hits = models.PositiveIntegerField(default=0, verbose_name="조회수")


class Review(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    grade = models.IntegerField(
        "숫자",
        default=1,
        help_text="1~5사이 값으로 입력하세요",
        validators=[MinValueValidator(1), MaxValueValidator(5)],
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 90},
    )


class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

reviews/forms.py
from django import forms
from .models import Store, Review, Comment


class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = [
            "store_name",
            "address",
            "phone_num",
            "menu",
            "image",
            "price",
            "parking",
            "week_time",
            "weekend",
            "last_order",
            "website",
        ]
        labels = {
            "store_name": "가게명",
            "address": "주소",
            "phone_num": "전화번호",
            "menu": "대표메뉴",
            "image": "사진",
            "price": "가격대",
            "parking": "주차",
            "week_time": "영업시간",
            "weekend": "휴일",
            "last_order": "마지막주문가능시간",
            "website": "홈페이지",
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "content",
            "grade",
            "image",
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]
        widgets = {
            "content": forms.Textarea(attrs={"class": "from-control", "rows": 1})
        }
        labels = {
            "content": "댓글",
        }

reviews/views.py
from django.shortcuts import render, redirect, get_object_or_404
from reviews.forms import ReviewForm, CommentForm
from .forms import StoreForm, CommentForm
from .models import Store, Review, Comment
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Avg
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_safe


# Create your views here.


@require_safe
def index(request):
    stores = Store.objects.order_by("-pk")
    paginator = Paginator(stores, 4)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "stores": stores,
        "page_obj": page_obj,
    }
    return render(request, "reviews/index.html", context)


@login_required
def store(request):
    if request.method == "POST":
        store_form = StoreForm(request.POST, request.FILES)
        if store_form.is_valid():
            store = store_form.save(commit=False)
            store.user = request.user
            store.save()
            messages.success(request, "가게 정보 작성이 완료되었습니다.")
            return redirect("reviews:index")
    else:
        store_form = StoreForm()
    context = {
        "store_form": store_form,
    }
    return render(request, "reviews/store.html", context)


def store_detail(request, store_pk):
    store = get_object_or_404(Store, pk=store_pk)
    reviews = store.review_set.all()
    reviews_ = store.review_set.all()

    if request.POST.get("grade-5"):
        reviews = store.review_set.filter(grade=5)
    elif request.POST.get("grade-4"):
        reviews = store.review_set.filter(grade=4)
    elif request.POST.get("grade-3"):
        reviews = store.review_set.filter(grade=3)
    elif request.POST.get("grade-2"):
        reviews = store.review_set.filter(grade=2)
    elif request.POST.get("grade-1"):
        reviews = store.review_set.filter(grade=1)
    elif request.POST.get("reset"):
        reviews = store.review_set.order_by("-pk")

    review_5 = store.review_set.filter(grade=5).count()
    review_4 = store.review_set.filter(grade=4).count()
    review_3 = store.review_set.filter(grade=3).count()
    review_2 = store.review_set.filter(grade=2).count()
    review_1 = store.review_set.filter(grade=1).count()

    review_ave = 0

    if review_ave == 0:
        review_ave = "평가 없음"

    if reviews_.count() > 0:
        ave = store.review_set.aggregate(Avg("grade"))

        # round(값, 표시하고 싶은 자리수)
        review_ave = round(ave["grade__avg"], 2)

    context = {
        "store": store,
        "reviews": reviews,
        "reviews_": reviews_,
        "review_5": review_5,
        "review_4": review_4,
        "review_3": review_3,
        "review_2": review_2,
        "review_1": review_1,
        "review_ave": review_ave,
    }
    response = render(request, "reviews/store_detail.html", context)
    store.hits += 1
    store.save()

    return response


@login_required
def store_delete(request, store_pk):
    store = get_object_or_404(Store, pk=store_pk)
    if request.user == store.user:
        if request.method == "POST":
            store.delete()
            messages.success(request, "가게 정보 삭제가 완료되었습니다.")
            return redirect("reviews:index")
    messages.success(request, "작성자만 삭제가 가능합니다.")
    return redirect("reviews:index")


@login_required
def store_update(request, store_pk):
    store = get_object_or_404(Store, pk=store_pk)
    if request.user == store.user:
        if request.method == "POST":
            store_form = StoreForm(request.POST, request.FILES, instance=store)
            if store_form.is_valid():
                form = store_form.save(commit=False)
                form.user = request.user
                form.save()
                messages.success(request, "가게 정보 수정이 완료되었습니다.")
                return redirect("reviews:store_detail", store_pk)
        else:
            store_form = StoreForm(instance=store)
        context = {
            "store_form": store_form,
        }
        return render(request, "reviews/store.html", context)
    else:
        messages.success(request, "작성자만 수정이 가능합니다.")
        return redirect("reviews:store_detail", store_pk)


@login_required
def review_create(request, store_pk):
    store = Store.objects.get(pk=store_pk)
    if request.method == "POST":
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.store = store
            review.user = request.user
            review.save()
            return redirect("reviews:store_detail", store.pk)
    else:
        review_form = ReviewForm()
    context = {
        "review_form": review_form,
    }
    return render(request, "reviews/review_form.html", context)


def review_detail(request, store_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)

    store = Store.objects.get(pk=store_pk)
    context = {
        "review": review,
        "store": store,
        "comment_form": CommentForm(),
        "comments": review.comment_set.all(),
    }
    return render(request, "reviews/review_detail.html", context)


@login_required
def review_delete(request, store_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user == review.user:
        if request.method == "POST":
            review.delete()
            return redirect("reviews:store_detail", store_pk)
    return redirect("reviews:store_detail", store_pk)


@login_required
def review_update(request, store_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user == review.user:
        if request.method == "POST":
            review_form = ReviewForm(request.POST, request.FILES, instance=review)
            if review_form.is_valid():
                form = review_form.save(commit=False)
                form.user = request.user
                form.save()
                return redirect("reviews:review_detail", store_pk, review_pk)
        else:
            review_form = ReviewForm(instance=review)
        context = {
            "review_form": review_form,
        }
        return render(request, "reviews/review_form.html", context)
    else:
        messages.warning(request, "작성자만 수정할 수 있습니다.")
        return redirect("articles:detail", review.pk)


def search(request):
    search = Store.objects.all().order_by("-pk")
    q = request.POST.get("q", "")
    if q:
        store_name = search.filter(store_name__icontains=q)
        address = search.filter(address__icontains=q)
        menu = search.filter(menu__icontains=q)
        price = search.filter(price__icontains=q)
        context = {
            "store_name": store_name,
            "address": address,
            "menu": menu,
            "price": price,
            "q": q,
        }
        return render(request, "reviews/search.html", context)
    else:
        return render(request, "reviews/search.html")


@login_required
def comment_create(request, store_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.review = review
            comment.user = request.user
            comment.save()
            return redirect("reviews:review_detail", store_pk, review_pk)
    return redirect("reviews:review_detail", store_pk, review_pk)


@login_required
def comment_delete(request, store_pk, review_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.user:
        if request.method == "POST":
            comment.delete()
            return redirect("reviews:review_detail", store_pk, review_pk)
    return redirect("reviews:review_detail", store_pk, review_pk)


def mz_gangnam(request):
    stores = Store.objects.filter(address__icontains="강남구")
    paginator = Paginator(stores, 7)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "stores": stores,
        "page_obj": page_obj,
    }
    return render(request, "reviews/index_gangnam.html", context)


@require_safe
def local_list(request):
    return render(request, "reviews/local_list.html")


def local_detail_gn(request):
    stores = Store.objects.filter(address__icontains="강남구")
    paginator = Paginator(stores, 5)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "stores": stores,
        "page_obj": page_obj,
        "local": "강남구",
    }
    return render(request, "reviews/local_detail.html", context)


def local_detail_sc(request):
    stores = Store.objects.filter(address__icontains="서초구")
    paginator = Paginator(stores, 5)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "stores": stores,
        "page_obj": page_obj,
        "local": "서초구",
    }
    return render(request, "reviews/local_detail.html", context)


def local_detail_ys(request):
    stores = Store.objects.filter(address__icontains="용산구")
    paginator = Paginator(stores, 5)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "stores": stores,
        "page_obj": page_obj,
        "local": "용산구",
    }
    return render(request, "reviews/local_detail.html", context)


def local_detail_sd(request):
    stores = Store.objects.filter(address__icontains="성동구")
    paginator = Paginator(stores, 5)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
{% comment %} <div class="text-center">
  <a href="{% url 'reviews:store' %}">[관리자]가게 생성</a>
</div> {% endcomment %}

<div class="container">
  <div class="row">
    {% for store in page_obj %}
    <div class="card col shadow mb-5 bg-body rounded g-3" style="max-width:280px;">
      <a href="{% url 'reviews:store_detail' store.pk %}" class="text-dark" style='text-decoration:none;'>
        {% if store.image %}
        <img src="{{ store.image.url }}" class="card-img-top my-2" alt=""
          style="width: 250px; height: 250px; border-radius: 16px">
        {% else %}
        <img src="https://dummyimage.com/1200x960/000000/c4c4c4" class="my4-2" style="width: 250; height: 250px;">
        {% endif %}
        <div class="card-body p-1">
          <h5 class="card-title m-0">{{store.store_name}}</h5>
          <hr class="m-1">
          <div class="my-2"> {{store.menu}}</div>
          <div class="my-2"> {{store.address}}</div>
        </div>
        <small class="d-flex justify-content-end mx-2 text-black-50">
          {{store.created_at|date:"o-m-d D"}}
        </small>
      </a>
    </div>
    {% endfor %}
  </div>

</div>
{% for menu in store.menu.all %}
<p>{{menu.menu_name}}</p>
{% endfor %}
{% comment %} 임시 {% endcomment %}
<div class="d-flex justify-content-center">
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; 처음</a>
      <a href="?page={{ page_obj.previous_page_number }}">이전</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">다음</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">마지막 &raquo;</a>
      {% endif %}
    </span>
  </div>
</div>



{% endblock content %}

reviews/templates/reviews/local_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
  <div class="container">
    <h1>여기는 지역별 맛집 리스트 입니다!</h1>

    <div class="row row-cols-1 row-cols-md-4 g-4">

      <div class="col">
        <div class="card h-100">
          <a href="{% url 'reviews:local_detail_gn' %}" style="text-decoration:none;" class="text-dark">
            <img src="https://cdn.pixabay.com/photo/2018/05/01/18/21/eclair-3366430_960_720.jpg" class="card-img-top" alt="...">
            <div class="card-body">
              <h3 class="card-title">강남구</h3>
            </div>
          </a>
        </div>
      </div>

      <div class="col">
        <div class="card h-100">
          <a href="{% url 'reviews:local_detail_sc' %}" style="text-decoration:none;" class="text-dark">
            <img src="https://cdn.pixabay.com/photo/2017/03/23/19/57/asparagus-2169305_960_720.jpg" class="card-img-top" alt="...">
            <div class="card-body">
              <h3 class="card-title">서초구</h3>
            </div>
          </a>
        </div>
      </div>

      <div class="col">
        <div class="card h-100">
          <a href="{% url 'reviews:local_detail_ys' %}" style="text-decoration:none;" class="text-dark">
            <img src="https://cdn.pixabay.com/photo/2014/10/19/20/59/hamburger-494706__340.jpg" class="card-img-top" alt="...">
            <div class="card-body">
              <h3 class="card-title">용산구</h3>
            </div>
          </a>
        </div>
      </div>

      <div class="col">
        <div class="card h-100">
          <a href="{% url 'reviews:local_detail_sd' %}" style="text-decoration:none;" class="text-dark">
            <img src="https://cdn.pixabay.com/photo/2017/01/26/02/06/platter-2009590__340.jpg" class="card-img-top" alt="...">
            <div class="card-body">
              <h3 class="card-title">성동구</h3>
            </div>
          </a>
        </div>
      </div>

      <div class="col">
        <div class="card h-100">
          <a href="{% url 'reviews:local_detail_no' %}" style="text-decoration:none;" class="text-dark">
            <img src="https://cdn.pixabay.com/photo/2014/08/14/14/21/shish-kebab-417994__340.jpg" class="card-img-top" alt="...">
            <div class="card-body">
              <h3 class="card-title">노원구</h3>
            </div>
          </a>
        </div>
      </div>

      <div class="col">
        <div class="card h-100">
          <a href="{% url 'reviews:local_detail_dj' %}" style="text-decoration:none;" class="text-dark">
            <img src="https://cdn.pixabay.com/photo/2017/12/10/14/47/pizza-3010062__340.jpg" class="card-img-top" alt="...">
            <div class="card-body">
              <h3 class="card-title">동작구</h3>
            </div>
          </a>
        </div>
      </div>

      <div class="col">
        <div class="card h-100">
          <a href="{% url 'reviews:local_detail_sp' %}" style="text-decoration:none;" class="text-dark">
            <img src="https://cdn.pixabay.com/photo/2016/03/05/19/02/salmon-1238248__340.jpg" class="card-img-top" alt="...">
            <div class="card-body">
              <h3 class="card-title">송파구</h3>
            </div>
          </a>
        </div>
      </div>

      <div class="col">
        <div class="card h-100">
          <a href="{% url 'reviews:local_detail_jn' %}" style="text-decoration:none;" class="text-dark">
            <img src="https://cdn.pixabay.com/photo/2014/08/14/14/21/shish-kebab-417994__340.jpg" class="card-img-top" alt="...">
            <div class="card-body">
              <h3 class="card-title">중랑구</h3>
            </div>
          </a>
        </div>
      </div>

    </div>

  </div>

{% endblock content %}

reviews/templates/reviews/price_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
  <div class="container">
    <h1>여기는 가격별 맛집 리스트 입니다!</h1>

    <div class="row row-cols-1 row-cols-md-5 g-4">

      <div class="col">
        <div class="card  h-200">
          <a href="{% url 'reviews:price_detail_1man' %}" style="text-decoration:none" class="text-dark">
            <img src="{% static '1만원.png' %}" class="card-img-top"  alt="...">
            <div class="card-body">
              <h2 class="card-title">만원 미만</h2>
            </div>
          </a>
        </div>
      </div>

      <div class="col">
        <div class="card h-200">
          <a href="{% url 'reviews:price_detail_2man' %}" style="text-decoration:none" class="text-dark">
            <img src="{% static '2만원.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h2 class="card-title">만원-2만원</h2>
            </div>
          </a>
        </div>
      </div>

      <div class="col">
        <div class="card h-200">
          <a href="{% url 'reviews:price_detail_3man' %}" style="text-decoration:none" class="text-dark">
            <img src="{% static '3만원.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h2 class="card-title">2만원-3만원</h2>
            </div>
          </a>
        </div>
      </div>

      <div class="col">
        <div class="card h-200">
          <a href="{% url 'reviews:price_detail_4man' %}" style="text-decoration:none" class="text-dark">
            <img src="{% static '4만원.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h2 class="card-title">3만원-4만원</h2>
            </div>
          </a>
        </div>
      </div>

      <div class="col">
        <div class="card h-200">
          <a href="{% url 'reviews:price_detail_4manup' %}" style="text-decoration:none" class="text-dark">
            <img src="{% static '5만원권.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h2 class="card-title">4만원 이상</h2>
            </div>
          </a>
        </div>
      </div>

    </div>

  </div>

{% endblock content %}

reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
  <div class="container">
    <h3>
      {% for i in review.user.profile_set.all %}
        <img src="{{ i.image.url }}" alt="" style="width: 40px; height: 40px; border-radius: 50px;">
      {% endfor %}
      <a href="{% url 'accounts:detail' review.user.pk %} " style="text-decoration:none" class="text-dark">{{ review.user.username }}</a>
    </h3>
    <p>별점 :
      {{ review.grade }}</p>
    <div class="row justify-content-between">
      <div class="">
        <p>{{review.updated_at|date:'Y-m-d a f'}}</p>
      </div>
      <form action="{% url 'reviews:review_delete' store.pk review.pk %}" method="POST">
        {% csrf_token %}
        <a href="{% url 'reviews:review_update' store.pk review.pk %}" class="btn btn-outline-primary" method="POST">수정</a>
        <input class="btn btn-outline-danger" type="submit" value="삭제">
        <a href="{% url 'reviews:store_detail' store.pk %}" class="btn btn-outline-secondary">뒤로</a>
      </form>
    </div>
    <p class="my-3">
      내용 :
      <b>
        <pre>{{ review.content }}</pre>
      </b>
    </p>
    {% if review.image %}
      <img src="{{ review.image.url }}" alt="{{review.image}}" width="250" height="180">
    {% else %}
      <img src="" alt="">
    {% endif %}

    {% if request.user.is_authenticated %}

      <div class='my-3 inline'>
        <form id="comment-form" action="{% url 'reviews:comment_create' store.pk review.pk %}" method="POST" class="border border-5 rounded p-3">
          {% csrf_token %}
          {% bootstrap_form comment_form %}
          <div class="text-end"><input class="btn btn-primary" type="submit" value="댓글 작성"></div>
        </form>
      </div>
    {% endif %}
{% comment %} 살펴보기 {% endcomment %}
    {% for comment in comments %}
      <div class="d-flex" style="height: 3rem;">
        <div class="col-2 align-self-center fs-7">
          {% for i in comment.user.profile_set.all %}
            <img src="{{ i.image.url }}" alt="" style="width: 40px; height: 40px; border-radius: 50px;">
          {% endfor %}
          <a href="{% url 'accounts:detail' comment.user.pk %} " style="text-decoration:none" class="text-dark">{{comment.user.username}}</a>
          
        </div>
        <div class="col-10 align-self-center fs-7">
          {{comment.content}}</div>
        {% if request.user == comment.user %}
          <form action="{% url 'reviews:comment_delete' store.pk review.pk comment.pk %}" method="POST" class="align-self-center">
            {% csrf_token %}
            <input class="" type="submit" value="삭제">
          </form>
        {% endif %}
      </div>
    {% endfor %}
  </div>

{% endblock content %}

reviews/templates/reviews/review_form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
  <div class='container'>
    <h1>글 작성</h1>
    <form action="" method='POST' enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form review_form %}
      {% bootstrap_button 'ok' %}
    </form>
  </div>
{% endblock content %}

reviews/templates/reviews/store.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}

<form action="" class="container" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form store_form %}
  <input type="submit" value="OK" class="btn btn-primary btn-md">
</form>

{% endblock content %}