accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.create, name="create"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:pk>/profile/", views.profile, name="profile"),
    path("profile/update/", views.profile_update, name="profile_update"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("store/", views.store, name="store"),
    path("<int:store_pk>/", views.store_detail, name="store_detail"),
    path("<int:store_pk>/delete", views.store_delete, name="store_delete"),
    path("<int:store_pk>/update", views.store_update, name="store_update"),
    path("<int:store_pk>/review_create/", views.review_create, name="review_create"),
    path(
        "<int:store_pk>/<int:review_pk>/review_detail/",
        views.review_detail,
        name="review_detail",
    ),
    path(
        "<int:store_pk>/<int:review_pk>/review_delete/",
        views.review_delete,
        name="review_delete",
    ),
    path(
        "<int:store_pk>/<int:review_pk>/review_detail/review_update/",
        views.review_update,
        name="review_update",
    ),
    path("search/", views.search, name="search"),
    path(
        "<int:store_pk>/<int:review_pk>/review_detail/comment/",
        views.comment_create,
        name="comment_create",
    ),
    path(
        "<int:store_pk>/<int:review_pk>/review_detail/comment/<int:comment_pk>/comment_delete",
        views.comment_delete,
        name="comment_delete",
    ),
    path("local_list/", views.local_list, name="local_list"),
    path("local_list/local_detail_gn", views.local_detail_gn, name="local_detail_gn"),
    path("local_list/local_detail_sc", views.local_detail_sc, name="local_detail_sc"),
    path("local_list/local_detail_ys", views.local_detail_ys, name="local_detail_ys"),
    path("local_list/local_detail_sd", views.local_detail_sd, name="local_detail_sd"),
    path("local_list/local_detail_no", views.local_detail_no, name="local_detail_no"),
    path("local_list/local_detail_dj", views.local_detail_dj, name="local_detail_dj"),
    path("local_list/local_detail_sp", views.local_detail_sp, name="local_detail_sp"),
    path("local_list/local_detail_jn", views.local_detail_jn, name="local_detail_jn"),
    path("price_list/", views.price_list, name="price_list"),
    path(
        "price_list/price_detail_1man",
        views.price_detail_1man,
        name="price_detail_1man",
    ),
    path(
        "price_list/price_detail_2man",
        views.price_detail_2man,
        name="price_detail_2man",
    ),
    path(
        "price_list/price_detail_3man",
        views.price_detail_3man,
        name="price_detail_3man",
    ),
    path(
        "price_list/price_detail_4man",
        views.price_detail_4man,
        name="price_detail_4man",
    ),
    path(
        "price_list/price_detail_4manup",
        views.price_detail_4manup,
        name="price_detail_4manup",
    ),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.conf import settings


class User(AbstractUser):
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )


class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(
        default="noimg.jpg",
        blank=True,
        processors=[Thumbnail(300, 300)],
        format="JPEG",
        options={"quality": 50},
    )

reviews/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings


# Create your models here.
class Store(models.Model):
    store_name = models.CharField(max_length=80)
    address = models.CharField(max_length=160)
    phone_num = models.CharField(max_length=80)
    menu = models.CharField(max_length=80)
    price = models.CharField(max_length=80, null=True, blank=True)
    parking = models.CharField(max_length=80, null=True, blank=True)
    week_time = models.CharField(max_length=80, null=True, blank=True)
    weekend = models.CharField(max_length=80, null=True, blank=True)
    last_order = models.CharField(max_length=80, null=True, blank=True)
    website = models.CharField(max_length=80, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(
        default="nostoreimg.jpg",
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 90},
    )
    hits = models.PositiveIntegerField(default=0, verbose_name="조회수")


class Review(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    grade = models.IntegerField(
        "숫자",
        default=1,
        help_text="1~5사이 값으로 입력하세요",
        validators=[MinValueValidator(1), MaxValueValidator(5)],
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 90},
    )


class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from .models import Profile
from django import forms


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["username", "email",]



class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
        )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreationForm, CustomUserChangeForm, ProfileForm
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .models import Profile
from django.http import JsonResponse

def create(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        profile = Profile()
        if form.is_valid():
            user = form.save()
            profile.user = user
            profile.save()
            auth_login(request, user)
            return redirect("reviews:index")

    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/create.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "reviews:index")
    else:
        form = AuthenticationForm()
    context = {
      "form": form,
    }
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("reviews:index")


# @login_required
# def follow(request, pk):
#     user = get_object_or_404(get_user_model(), pk=pk)
#     if request.user == user:
#         messages.warning(request, "자추금지!!!")
#         return redirect("accounts:detail", pk)
#     if request.user in user.followers.all():
#         user.followers.remove(request.user)
#     else:
#         user.followers.add(request.user)
#     return redirect("accounts:detail", pk)


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    profile = user.profile_set.all()[0]
    user_point = (user.review_set.count() * 5) + ((user.comment_set.count() * 1))
    context = {
        "user": user,
        "profile": profile,
        "user_point": user_point,
    }
    return render(request, "accounts/detail.html", context)


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, "accounts/update.html", context)


@login_required
def profile(request, pk):  # 프로필
    user = get_user_model().objects.get(pk=pk)
    reviews = user.review_set.all()
    comments = user.comment_set.all()
    profile = user.profile_set.all()[0]
    context = {
        "reviews": reviews,
        "comments": comments,
        "profile": profile,
    }
    return render(request, "accounts/profile.html", context)


@login_required
def profile_update(request):  # 프로필 업데이트
    user = get_user_model().objects.get(pk=request.user.pk)
    current_user = user.profile_set.all()[0]
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save()
            return redirect("reviews:index")
    else:
        form = ProfileForm(instance=current_user)
    context = {
        "profile_form": form,
    }
    return render(request, "accounts/profile_update.html", context)

def follow(request, pk):
  if request.user.is_authenticated:
    User = get_user_model()
    me = request.user
    you = User.objects.get(pk=pk)
    if me != you:
      if you.followers.filter(pk=me.pk).exists():
        you.followers.remove(me)
        is_followed = False
      else:
        you.followers.add(me)
        is_followed = True
      context = {
        'is_followed': is_followed,
        'followers_count': you.followers.count(),
        'followings_count': you.followings.count(),
      }
      return JsonResponse(context)
    return redirect('accounts:detail', you.username)
  return redirect('accounts:login')

accounts/templates/accounts/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container">
  <h1>회원가입</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {%bootstrap_form form%}
    {%bootstrap_button button_type="submit" content="회원가입"%}
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}


<div class="container text-center" style="max-width:800px;">
  <div class="row">
    <div class="col-4 p-0">
      {% for i in user.profile_set.all %}
      {% if i.image %}
      <img style="width:200px; " src="{{ i.image.url }}" alt="" class="rounded-circle">
      {% else %}
      <img src="https://dummyimage.com/1200x960/000000/c4c4c4" class="rounded-circle"
        style="width: 200px; height: 200px;">
      {% endif %}
      {% endfor %}
    </div>
    <div class="col-7 p-2">
      <div class="d-flex justify-content-evenly">
        <div class="col align-items-center fw-bold fs-4">
          {{ user.username }}
          <p>유저 포인트 : {{user_point}} </p>
          <p>{{user.email}}
            {% if request.user == user %}
            <a action href="{% url 'accounts:profile_update' %}" class='btn btn-outline-success ms-5'>프로필 수정</a>
            {% endif %}
          </p>
        </div>
        <div class="col">
          {% if request.user != user %}
          <form id="follow-form" data-user-id="{{ request.user.pk }}" method="POST">
            {% if request.user.is_authenticated %}
            {% csrf_token %}
            {% if request.user in user.followers.all %}
            <input class="btn btn-dark btn-lg" type="submit" value="팔로우 취소" style="width: 120px;">
            {% else %}
            <input class="btn btn-dark btn-lg" type="submit" value="팔로우" style="width: 120px;">
            {% endif %}
          </form>
          {% else %}
          {%bootstrap_button button_type="submit" content="로그인 필요합니다."%}
          {% endif %}
          {% endif %}
          </form>

        </div>
      </div>
      <div class="d-flex justify-content-center align-items-center mt-5">
        <div class="col">
          리뷰글 {{ user.review_set.count }}
        </div>
        <div class="col">
          댓글 {{ user.comment_set.count }}
        </div>
        <div class="col">
          <div style="cursor:pointer" class="" data-bs-toggle="modal" data-bs-target="#exampleModal2">
            팔로우<span id="followings-count"> {{ user.followings.count }}</span>
          </div>
        </div>
        <div class="col">
          <div style="cursor:pointer" class="" data-bs-toggle="modal" data-bs-target="#exampleModal">
            팔로워 <span id="followers-count">{{ user.followers.count }}</span>
          </div>
        </div>
      </div>
      {% comment %} {% endcomment %}
      <!-- Button trigger modal -->


      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">팔로워 목록</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              {% for i in user.followers.all %}
              <div>{{ i }}</div>
              {% endfor %}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
            </div>
          </div>
        </div>
      </div>
      <!-- Modal2 -->
      <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel2" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel2">팔로우 목록</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              {% for i in user.followings.all %}
              <div>{{ i }}</div>
              {% endfor %}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
            </div>
          </div>
        </div>
      </div>

      {% comment %} {% endcomment %}

    </div>
  </div>
  <div class="fs-3 text-center my-5"><span class="fs-2 text-warning">{{ user.username }}</span>의 리뷰</div>
  <div class="container mb-5">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 gap-5">
      {% for i in user.review_set.all %}
      <div class="card m-0" style="width: 18rem; min-height:150px; max-height:1000px;">
        <a class="text-dark" href="{% url 'reviews:store_detail' i.store.pk %}" style="text-decoration:none;">
          {% if i.image %}
          <div class="d-flex justify-content-center mt-1">
            <img src="{{ i.image.url }}" alt="" style="width: 200px; height: 200px; border-radius: 24px">
          </div>
          {% else %}
          <div class="d-flex justify-content-center mt-1">
            <img src="https://dummyimage.com/1200x960/000000/c4c4c4" class=""
              style="width: 200px; height: 200px; border-radius: 24px">
          </div>
          {% endif %}
          <div class="card-body">
            <div class="fs-3">{{ i.store.store_name }}</div>
            <div>{{ i.content|truncatewords:10 }}</div>
          </div>
          <small class="fs-7 d-flex justify-content-end">
            {{ i.created_at|date:"o-m-d D" }}
          </small>
        </a>
      </div>
      {% endfor %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>
      const form = document.querySelector("#follow-form")
      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

      form.addEventListener('submit', function (event) {
        event.preventDefault()
        const userId = event.target.dataset.userId

        axios({
          method: 'post',
          url: `/accounts/${userId}/follow/`,
          headers: {
            'X-CSRFToken': csrftoken
          }
        })
          .then((response) => {
            const isFollowed = response.data.is_followed
            const followBtn = document.querySelector('#follow-form > input[type=submit]')
            if (isFollowed === true) {
              followBtn.value = '팔로우 취소'
            } else {
              followBtn.value = '팔로우'
            }
            const followerCountTag = document.querySelector('#followers-count')
            const followingCountTag = document.querySelector('#followings-count')
            const followersCount = response.data.followers_count
            const followingsCount = response.data.followings_count
            followerCountTag.innerText = followersCount
            followingCountTag.innerText = followingsCount
          })
          .catch((error) => {
            console.log(error.response)
          })
      })

    </script>

    {% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<h1>로그인</h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="OK" %}
</form>

{% endblock content %}

accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h1>프로필 수정하기</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form profile_form %}
    <button type="submit" class="btn btn-outline-dark">수정하기</button>
  </form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<h1>프로필 업데이트</h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock content %}