accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.create, name="create"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:pk>/profile/", views.profile, name="profile"),
    path("profile/update/", views.profile_update, name="profile_update"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("store/", views.store, name="store"),
    path("<int:store_pk>/", views.store_detail, name="store_detail"),
    path("<int:store_pk>/delete", views.store_delete, name="store_delete"),
    path("<int:store_pk>/update", views.store_update, name="store_update"),
    path("<int:store_pk>/review_create/", views.review_create, name="review_create"),
    path(
        "<int:store_pk>/<int:review_pk>/review_detail/",
        views.review_detail,
        name="review_detail",
    ),
    path(
        "<int:store_pk>/<int:review_pk>/review_delete/",
        views.review_delete,
        name="review_delete",
    ),
    path(
        "<int:store_pk>/<int:review_pk>/review_detail/review_update/",
        views.review_update,
        name="review_update",
    ),
    path("search/", views.search, name="search"),
    path(
        "<int:store_pk>/<int:review_pk>/review_detail/comment/",
        views.comment_create,
        name="comment_create",
    ),
    path(
        "<int:store_pk>/<int:review_pk>/review_detail/comment/<int:comment_pk>/comment_delete",
        views.comment_delete,
        name="comment_delete",
    ),
    path("local_list/", views.local_list, name="local_list"),
    path("local_list/local_detail_gn", views.local_detail_gn, name="local_detail_gn"),
    path("local_list/local_detail_sc", views.local_detail_sc, name="local_detail_sc"),
    path("local_list/local_detail_ys", views.local_detail_ys, name="local_detail_ys"),
    path("local_list/local_detail_sd", views.local_detail_sd, name="local_detail_sd"),
    path("local_list/local_detail_no", views.local_detail_no, name="local_detail_no"),
    path("local_list/local_detail_dj", views.local_detail_dj, name="local_detail_dj"),
    path("local_list/local_detail_sp", views.local_detail_sp, name="local_detail_sp"),
    path("local_list/local_detail_jn", views.local_detail_jn, name="local_detail_jn"),
    path("price_list/", views.price_list, name="price_list"),
    path(
        "price_list/price_detail_1man",
        views.price_detail_1man,
        name="price_detail_1man",
    ),
    path(
        "price_list/price_detail_2man",
        views.price_detail_2man,
        name="price_detail_2man",
    ),
    path(
        "price_list/price_detail_3man",
        views.price_detail_3man,
        name="price_detail_3man",
    ),
    path(
        "price_list/price_detail_4man",
        views.price_detail_4man,
        name="price_detail_4man",
    ),
    path(
        "price_list/price_detail_4manup",
        views.price_detail_4manup,
        name="price_detail_4manup",
    ),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.conf import settings


class User(AbstractUser):
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )


class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(
        default="noimg.jpg",
        blank=True,
        processors=[Thumbnail(300, 300)],
        format="JPEG",
        options={"quality": 50},
    )

templates/base.html
{% load django_bootstrap5 %} {% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Jua&family=Noto+Sans+KR:wght@500&display=swap"
    rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'style.css' %}?{% now 'U'%}" />
  <title>Document</title>
  {% bootstrap_css %}
</head>

<body>
  {% comment %} navbar - fixed-top {% endcomment %}
  <nav class="navbar fixed-top" style="background-color: #ffba08;">
    <div class="container">
      <div class="col-3 ">
        <a class="navbar-brand fw-bold fs-4" href="{% url 'reviews:index' %}">맛짱</a>
      </div>
      <div class="col-4">
        <form class="d-flex" role="search" action="{% url 'reviews:search' %}" method="POST">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q"
            value="{{q}}">
          <button class="btn btn-outline-dark" type="submit">Search</button>
        </form>
      </div>
      <div class="col-3 m-1">
        <a class="navbar-brand fw-bold" href="{% url 'reviews:local_list' %}">맛집리스트</a>
        <a class="navbar-brand fw-bold" href="{% url 'reviews:price_list' %}">가격대별</a>
      </div>
      
      <div class="col-1">
        <div class="nav-item dropdown user-menu-parent ">
          {% if request.user.is_authenticated %}
          <a aria-expanded="false" class="nav-link dropdown-toggle user-menu-link loggedin" href="#"
            data-bs-toggle="dropdown" aria-haspopup="true" style="color: #ffba08;">
            {% for i in request.user.profile_set.all %}
            {% if i.image %}
            <img src="{{ i.image.url }}" alt="" style="width: 40px; height: 40px; border-radius: 50px;">
            {% else %}
            <img src="https://dummyimage.com/1200x960/000000/c4c4c4" class=""
              style="width: 40px; height: 40px; border-radius: 50px;">
            {% endif %}
            {% endfor %}
            {% else %}
            <a aria-expanded="false" class="nav-link dropdown-toggle user-menu-link loggedin" href="#"
              data-bs-toggle="dropdown" aria-haspopup="true" style="color: #ffba08;">
              <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                class="bi bi-person-circle" viewBox="0 0 16 16" style="color: #000000;">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                <path fill-rule="evenodd"
                  d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
              </svg>
              {% endif %}
              {% if request.user.is_authenticated %}
              <span>
                <span class="text-decoration: none" style="color: #000000;">{{ request.user }}</span>
              </span>
              {% else %}
              <span class="text-decoration: none" style="color: #000000;">로그인이 필요합니다</span>
              {% endif %}
            </a>
            <ul class="dropdown-menu user-dropdown-menu right">
              {% if request.user.is_authenticated %}
              <li><a class="navbar-brand fw-bold" href="{% url 'accounts:detail' request.user.pk %}">회원정보</a></li>
              <li><a class="navbar-brand fw-bold" href="{% url 'accounts:update' %}">회원정보수정</a></li>
              <li><a class="navbar-brand fw-bold" href="{% url 'accounts:logout' %}">로그아웃</a></li>
              <div class="d-flex" style="align-items:center">
                {% else %}
                <li><a class="navbar-brand fw-bold" href="{% url 'accounts:login' %}">로그인</a></li>
                <li><a class="navbar-brand fw-bold" href="{% url 'accounts:create' %}">회원가입</a></li>
                {% endif %}
            </ul>
        </div>
      </div>
    </div>
  </nav>
  <br>
  <br>
  <br>
  <br>
  {% if messages %}
  <div class="text-center"> {% for message in messages %}
    {{ message.tags }} {{message.message }}
      {% endfor %}
  </div>
  {% endif %}
  {% block content %} {% endblock content %}
  {% bootstrap_javascript %}
</body>

</html>